spring.application.name=antirisk-bot

telegram.userName=@tm_tb_bot
telegram.botToken=5407132811:AAGnef2jSemr6Oyhk-MruQAn2paQhFoejBY

spring.datasource.url=jdbc:postgresql://localhost:5432/test_antirisk_bot_db
spring.datasource.username=test_antirisk_bot_admin
spring.datasource.password=8146

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

antiriskbot.bk-mkx-url=https://ijo3rp0g9hn4n.com/LiveFeed/Mb_GetGamesZip?champs=1252965&country=1&mode=2&withSubGames=true&grMode=2&groupEvents=true
antiriskbot.mkx-event-url=https://ijo3rp0g9hn4n.com/MainFeedLive/mb/cyber/v1/game?cfView=3&country=1&gameId=%s&gr=0&lng=ru_RU&ref=1
