spring.application.name=antirisk-bot

telegram.userName=@tm_tb_bot
telegram.botToken=5407132811:AAGnef2jSemr6Oyhk-MruQAn2paQhFoejBY

#Настройка proxy
telegram.bot.proxy.host=185.89.41.205
telegram.bot.proxy.port=8000
telegram.bot.proxy.user=Vkjy9N
telegram.bot.proxy.pass=bacgLQ
telegram.bot.proxy.type=HTTP

spring.datasource.url=jdbc:postgresql://localhost:5432/test_antirisk_bot_db
spring.datasource.username=test_antirisk_bot_admin
spring.datasource.password=8146

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

antiriskbot.bk-mkx-url=https://s2zg0bhwgyuuin.com/LiveFeed/Mb_GetGamesZip?champs=1252965&country=1&mode=2&withSubGames=true&grMode=2&groupEvents=true
antiriskbot.mkx-event-url=https://s2zg0bhwgyuuin.com/MainFeedLive/mb/cyber/v1/game?cfView=3&country=1&gameId=%s&gr=0&lng=ru_RU&ref=1&whence=22

logging.level.root=INFO
logging.level.com.worldbet=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
